#Minecraft server properties
server-port=${SERVER_PORT}
motd=${SERVER_MOTD}
enable-rcon=true
rcon.port=${RCON_PORT}
rcon.password=${RCON_PASSWORD}
gamemode=survival
difficulty=normal
max-players=20
online-mode=false
enable-command-block=false
view-distance=10
simulation-distance=10
